import type { FastifyInstance } from 'fastify';
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';

import {
  createAdminUser,
  createIntegrationApp,
  createPatientUser,
  parisDate,
  resetIntegrationDb,
  type TestUser,
  trpcData,
  trpcError,
  trpcMutate,
  trpcQuery,
} from './harness';

// `vi.mock` is hoisted above these imports, so every module below resolves the
// database through the PGlite double.
vi.mock('../../src/db', () => import('./db.mock'));

interface Schedule {
  id: string;
  intakeTime: string;
  intakeMoment: string;
  quantity: string;
}

interface MedicationDetail {
  id: string;
  medicationName: string;
  startDate: string;
  endDate: string | null;
  isActive: boolean;
  schedules: Schedule[];
}

interface Intake {
  id: string;
  patientMedicationId: string;
  scheduledTime: string;
  status: string;
  medicationName: string;
}

const UNKNOWN_UUID = '00000000-0000-4000-8000-000000000000';

/**
 * Journey: a patient fills their pillbox, follows the daily intakes and edits the schedules.
 *
 * The intakes for the current day are generated by the service itself, so the specs below also
 * cover that generation and the status transitions attached to it.
 */
describe('integration: pillbox journey', () => {
  let app: FastifyInstance;
  let patient: TestUser;

  beforeAll(async () => {
    app = await createIntegrationApp();
  });

  afterAll(async () => {
    await app.close();
  });

  beforeEach(async () => {
    await resetIntegrationDb();
    patient = await createPatientUser(app);
  });

  function addMedication(
    user: TestUser,
    overrides: Partial<{
      medicationName: string;
      startDate: string;
      endDate: string | null;
      schedules: Array<{ intakeTime: string; intakeMoment?: string; quantity?: string }>;
    }> = {},
  ) {
    return trpcMutate(
      app,
      'pillbox.createMedication',
      {
        medicationName: overrides.medicationName ?? 'Doliprane 1000 mg',
        startDate: overrides.startDate ?? parisDate(),
        ...(overrides.endDate === undefined ? {} : { endDate: overrides.endDate }),
        schedules: overrides.schedules ?? [
          { intakeTime: '08:00', intakeMoment: 'MORNING', quantity: '1' },
          { intakeTime: '20:00', intakeMoment: 'EVENING', quantity: '2' },
        ],
      },
      user.cookie,
    );
  }

  describe('adding a medication', () => {
    it('creates the medication with its schedules', async () => {
      const res = await addMedication(patient);

      expect(res.statusCode).toBe(200);
      const detail = trpcData<MedicationDetail>(res);
      expect(detail).toMatchObject({ medicationName: 'Doliprane 1000 mg', isActive: true });
      expect(detail.schedules.map(schedule => schedule.intakeTime)).toEqual(['08:00', '20:00']);
    });

    it('lists the medication in the patient pillbox', async () => {
      await addMedication(patient);

      const res = await trpcQuery(app, 'pillbox.listMine', {}, patient.cookie);

      const { items, total } = trpcData<{ items: MedicationDetail[]; total: number }>(res);
      expect(total).toBe(1);
      expect(items[0].medicationName).toBe('Doliprane 1000 mg');
    });

    it('rejects a medication without any schedule', async () => {
      const res = await addMedication(patient, { schedules: [] });

      expect(res.statusCode).toBe(400);
      expect(trpcError(res).message).toContain('At least one schedule is required');
    });

    it('rejects an empty medication name', async () => {
      const res = await addMedication(patient, { medicationName: '' });

      expect(res.statusCode).toBe(400);
    });

    it('rejects a start date that is not YYYY-MM-DD', async () => {
      const res = await addMedication(patient, { startDate: '01/01/2026' });

      expect(res.statusCode).toBe(400);
      expect(trpcError(res).message).toContain('Must be YYYY-MM-DD');
    });

    it('rejects an intake time that is not HH:mm', async () => {
      const res = await addMedication(patient, { schedules: [{ intakeTime: '8h' }] });

      expect(res.statusCode).toBe(400);
    });

    it('rejects an end date before the start date', async () => {
      const res = await addMedication(patient, {
        startDate: parisDate(10),
        endDate: parisDate(2),
      });

      expect(res.statusCode).toBe(400);
      expect(trpcError(res).message).toBe('End date must be after start date');
    });

    it('rejects an unauthenticated creation', async () => {
      const res = await trpcMutate(app, 'pillbox.createMedication', {
        medicationName: 'Doliprane',
        startDate: parisDate(),
        schedules: [{ intakeTime: '08:00' }],
      });

      expect(res.statusCode).toBe(401);
    });
  });

  describe('daily intakes', () => {
    it('generates one pending intake per schedule for today', async () => {
      await addMedication(patient);

      const res = await trpcQuery(app, 'pillbox.today', {}, patient.cookie);

      const { date, intakes } = trpcData<{ date: string; intakes: Intake[] }>(res);
      expect(date).toBe(parisDate());
      expect(intakes).toHaveLength(2);
      expect(intakes.every(intake => intake.status === 'PENDING')).toBe(true);
    });

    it('does not generate intakes for a medication starting later', async () => {
      await addMedication(patient, { startDate: parisDate(3) });

      const res = await trpcQuery(app, 'pillbox.today', {}, patient.cookie);

      expect(trpcData<{ intakes: Intake[] }>(res).intakes).toHaveLength(0);
    });

    it('marks an intake as taken', async () => {
      await addMedication(patient);
      const [intake] = trpcData<{ intakes: Intake[] }>(
        await trpcQuery(app, 'pillbox.today', {}, patient.cookie),
      ).intakes;

      const res = await trpcMutate(
        app,
        'pillbox.markIntakeTaken',
        { id: intake.id, notes: 'after breakfast' },
        patient.cookie,
      );

      expect(res.statusCode).toBe(200);
      expect(trpcData<{ status: string; notes: string | null }>(res)).toMatchObject({
        status: 'TAKEN',
        notes: 'after breakfast',
      });
    });

    it('marks an intake as skipped', async () => {
      await addMedication(patient);
      const [intake] = trpcData<{ intakes: Intake[] }>(
        await trpcQuery(app, 'pillbox.today', {}, patient.cookie),
      ).intakes;

      const res = await trpcMutate(
        app,
        'pillbox.markIntakeSkipped',
        { id: intake.id },
        patient.cookie,
      );

      expect(trpcData<{ status: string }>(res).status).toBe('SKIPPED');
    });

    it('rejects marking the same intake twice', async () => {
      await addMedication(patient);
      const [intake] = trpcData<{ intakes: Intake[] }>(
        await trpcQuery(app, 'pillbox.today', {}, patient.cookie),
      ).intakes;
      await trpcMutate(app, 'pillbox.markIntakeTaken', { id: intake.id }, patient.cookie);

      const res = await trpcMutate(
        app,
        'pillbox.markIntakeTaken',
        { id: intake.id },
        patient.cookie,
      );

      expect(res.statusCode).toBe(400);
      expect(trpcError(res).message).toBe('Cannot mark as taken: current status is TAKEN');
    });

    it('reports NOT_FOUND for an unknown intake', async () => {
      const res = await trpcMutate(
        app,
        'pillbox.markIntakeTaken',
        { id: UNKNOWN_UUID },
        patient.cookie,
      );

      expect(res.statusCode).toBe(404);
      expect(trpcError(res).message).toBe('Intake not found');
    });

    it('rejects marking an intake belonging to another patient', async () => {
      await addMedication(patient);
      const [intake] = trpcData<{ intakes: Intake[] }>(
        await trpcQuery(app, 'pillbox.today', {}, patient.cookie),
      ).intakes;
      const other = await createPatientUser(app);

      const res = await trpcMutate(app, 'pillbox.markIntakeTaken', { id: intake.id }, other.cookie);

      expect(res.statusCode).toBe(403);
      expect(trpcError(res).message).toBe('Access denied');
    });

    it('rejects a note longer than 500 characters', async () => {
      await addMedication(patient);
      const [intake] = trpcData<{ intakes: Intake[] }>(
        await trpcQuery(app, 'pillbox.today', {}, patient.cookie),
      ).intakes;

      const res = await trpcMutate(
        app,
        'pillbox.markIntakeTaken',
        { id: intake.id, notes: 'x'.repeat(501) },
        patient.cookie,
      );

      expect(res.statusCode).toBe(400);
    });
  });

  describe('intake history', () => {
    it('reports the day as fully taken once every intake is taken', async () => {
      await addMedication(patient, { schedules: [{ intakeTime: '08:00' }] });
      const [intake] = trpcData<{ intakes: Intake[] }>(
        await trpcQuery(app, 'pillbox.today', {}, patient.cookie),
      ).intakes;
      await trpcMutate(app, 'pillbox.markIntakeTaken', { id: intake.id }, patient.cookie);

      const res = await trpcQuery(
        app,
        'pillbox.intakeHistory',
        { from: parisDate(), to: parisDate() },
        patient.cookie,
      );

      expect(
        trpcData<{ days: Array<{ date: string; allTaken: boolean | null }> }>(res).days,
      ).toEqual([{ date: parisDate(), allTaken: true }]);
    });

    it('reports the day as incomplete while an intake is pending', async () => {
      await addMedication(patient);
      await trpcQuery(app, 'pillbox.today', {}, patient.cookie);

      const res = await trpcQuery(
        app,
        'pillbox.intakeHistory',
        { from: parisDate(), to: parisDate() },
        patient.cookie,
      );

      expect(trpcData<{ days: Array<{ allTaken: boolean | null }> }>(res).days[0].allTaken).toBe(
        false,
      );
    });

    it('rejects an inverted date range', async () => {
      const res = await trpcQuery(
        app,
        'pillbox.intakeHistory',
        { from: parisDate(5), to: parisDate(1) },
        patient.cookie,
      );

      expect(res.statusCode).toBe(400);
      expect(trpcError(res).message).toBe('from must be before or equal to to');
    });
  });

  describe('editing schedules', () => {
    it('adds a schedule to an existing medication', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));

      const res = await trpcMutate(
        app,
        'pillbox.addSchedule',
        { patientMedicationId: medication.id, intakeTime: '13:00', intakeMoment: 'NOON' },
        patient.cookie,
      );

      expect(res.statusCode).toBe(200);
      expect(trpcData<Schedule>(res)).toMatchObject({ intakeTime: '13:00', intakeMoment: 'NOON' });
    });

    it('updates the time of a schedule', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));

      const res = await trpcMutate(
        app,
        'pillbox.updateSchedule',
        { id: medication.schedules[0].id, intakeTime: '09:30' },
        patient.cookie,
      );

      expect(trpcData<Schedule>(res).intakeTime).toBe('09:30');
    });

    it('deletes a schedule and keeps the medication', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));

      const res = await trpcMutate(
        app,
        'pillbox.deleteSchedule',
        { id: medication.schedules[1].id },
        patient.cookie,
      );

      expect(res.statusCode).toBe(200);
      const detail = trpcData<MedicationDetail>(
        await trpcQuery(app, 'pillbox.detail', { id: medication.id }, patient.cookie),
      );
      expect(detail.schedules).toHaveLength(1);
      expect(detail.schedules[0].intakeTime).toBe('08:00');
    });

    it('keeps the already generated intakes when a schedule is deleted', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));
      const before = trpcData<{ intakes: Intake[] }>(
        await trpcQuery(app, 'pillbox.today', {}, patient.cookie),
      ).intakes;
      expect(before).toHaveLength(2);

      await trpcMutate(
        app,
        'pillbox.deleteSchedule',
        { id: medication.schedules[1].id },
        patient.cookie,
      );

      const history = trpcData<{ days: Array<{ date: string; allTaken: boolean | null }> }>(
        await trpcQuery(
          app,
          'pillbox.intakeHistory',
          { from: parisDate(), to: parisDate() },
          patient.cookie,
        ),
      );
      expect(history.days[0].allTaken).toBe(false);
    });

    it('rejects an invalid weekday', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));

      const res = await trpcMutate(
        app,
        'pillbox.addSchedule',
        { patientMedicationId: medication.id, intakeTime: '13:00', weekday: 9 },
        patient.cookie,
      );

      expect(res.statusCode).toBe(400);
    });

    it('rejects adding a schedule to a medication of another patient', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));
      const other = await createPatientUser(app);

      const res = await trpcMutate(
        app,
        'pillbox.addSchedule',
        { patientMedicationId: medication.id, intakeTime: '13:00' },
        other.cookie,
      );

      expect(res.statusCode).toBe(403);
      expect(trpcError(res).message).toBe('Access denied');
    });

    it('reports NOT_FOUND when updating an unknown schedule', async () => {
      const res = await trpcMutate(
        app,
        'pillbox.updateSchedule',
        { id: UNKNOWN_UUID, intakeTime: '09:30' },
        patient.cookie,
      );

      expect(res.statusCode).toBe(404);
      expect(trpcError(res).message).toBe('Schedule not found');
    });
  });

  describe('medication access control', () => {
    it('returns the detail to its owner', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));

      const res = await trpcQuery(app, 'pillbox.detail', { id: medication.id }, patient.cookie);

      expect(trpcData<MedicationDetail>(res).id).toBe(medication.id);
    });

    it('hides the detail from another patient', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));
      const other = await createPatientUser(app);

      const res = await trpcQuery(app, 'pillbox.detail', { id: medication.id }, other.cookie);

      expect(res.statusCode).toBe(403);
      expect(trpcError(res).message).toBe('Access denied');
    });

    it('lets an admin read the detail', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));
      const admin = await createAdminUser(app);

      const res = await trpcQuery(app, 'pillbox.detail', { id: medication.id }, admin.cookie);

      expect(res.statusCode).toBe(200);
    });

    it('deactivates a medication through an update', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));

      const res = await trpcMutate(
        app,
        'pillbox.updateMedication',
        { id: medication.id, isActive: false },
        patient.cookie,
      );

      expect(trpcData<{ isActive: boolean }>(res).isActive).toBe(false);
    });

    it('deletes a medication and its schedules', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));

      const deleted = await trpcMutate(
        app,
        'pillbox.deleteMedication',
        { id: medication.id },
        patient.cookie,
      );
      expect(deleted.statusCode).toBe(200);

      const res = await trpcQuery(app, 'pillbox.detail', { id: medication.id }, patient.cookie);
      expect(res.statusCode).toBe(404);
      expect(trpcError(res).message).toBe('Medication not found');
    });

    it('rejects deleting a medication of another patient', async () => {
      const medication = trpcData<MedicationDetail>(await addMedication(patient));
      const other = await createPatientUser(app);

      const res = await trpcMutate(
        app,
        'pillbox.deleteMedication',
        { id: medication.id },
        other.cookie,
      );

      expect(res.statusCode).toBe(403);
      expect(trpcError(res).message).toBe('Access denied');
    });
  });
});
