catalog:
  react: 19.2.3
  react-dom: 19.2.3
  react-router: 7.12.0
  "@react-router/dev": 7.12.0
  "@react-router/fs-routes": 7.12.0
  "@react-router/node": 7.12.0
  "@react-router/serve": 7.12.0
  "@tanstack/react-form": 1.27.7
  "@tanstack/react-query": 5.90.17
  "@tanstack/react-query-devtools": 5.91.1
  "@trpc/client": 11.8.1
  "@trpc/server": 11.8.1
  better-auth: 1.4.18
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  isbot: 5.1.32
  lucide-react: 0.556.0
  next-themes: 0.4.6
  radix-ui: 1.4.3
  shadcn: 3.6.3
  sonner: 2.0.7
  tailwind-merge: 3.4.0
  tw-animate-css: 1.4.0
  zod: 4.3.5
  vite-tsconfig-paths: 5.1.4
  typescript: 5.9.3
  "@types/node": 24.3.1
  eslint: 9.37.0
  knip: 5.64.1
  prettier: 3.6.2
  depcheck: 1.4.7
  "@faker-js/faker": 10.1.0
  vitest: 3.2.4
  "@vitest/ui": 3.2.4

nodeLinker: node-modules

plugins:
  - checksum: 28bda5b6ec07f7c900b5b94273bbeab5992bf94d301071e0638c6bd051a16071124aebe9927e99eb2a7178e2b99ebb3ef9ac206b07dc3fddd5d63cf5b69e39b1
    path: .yarn/plugins/@yarnpkg/plugin-catalogs.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-catalogs/main/bundles\
      /%40yarnpkg/plugin-catalogs.js"
