apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: backend:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
          env:
            - name: BETTER_AUTH_SECRET
              value: "0YyafjMCfnADbUK9zSlf7t8GVnS2u9bMutPMi6GPEqukTkd4QWf78iv1QpoJJOamLpxfJJq/L+0b7PwiCu4Xbg=="
            - name: CORS_ORIGIN
              value: "*"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
