name: "🚀 PR → 💬 Discord Notifications"
on:
    pull_request_review:
        types: [submitted]
    pull_request:
        types: [opened, closed, ready_for_review, converted_to_draft, reopened]

jobs:
    notify:
        uses: ESP-Corevia/.github/.github/workflows/pr_review_notification.yml@master
        secrets: inherit
